PROMPT ================================
PROMPT Blood Donation Finalization Script
PROMPT Adds audit, validation, role views, dashboard views
PROMPT ================================

-- Re-runnable drop helpers
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_blood_units_validate';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_blood_units_audit_status';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_transfusion_requests_validate';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_unit_transfers_validate';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_match_dispatches_validate';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_admin_request_overview';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_staff_request_overview';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_dashboard_inventory_by_status';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_dashboard_requests_by_status';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_dashboard_dispatch_performance';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE blood_unit_status_audit';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- 1) Audit table for status history tracking
CREATE TABLE blood_unit_status_audit (
    audit_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id              NUMBER NOT NULL,
    old_status           VARCHAR2(50),
    new_status           VARCHAR2(50) NOT NULL,
    changed_at           DATE DEFAULT SYSDATE NOT NULL,
    changed_by           VARCHAR2(255) DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER') NOT NULL
);
/

-- 2) Validation on BLOOD_UNITS:
--    - Prevent impossible states for expired units
--    - Restrict status values
CREATE OR REPLACE TRIGGER trg_blood_units_validate
BEFORE INSERT OR UPDATE ON blood_units
FOR EACH ROW
BEGIN
    IF :NEW.status IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'BLOOD_UNITS.status cannot be NULL.');
    END IF;

    IF :NEW.status NOT IN ('Available', 'Reserved', 'Transfused', 'Expired', 'Discarded') THEN
        RAISE_APPLICATION_ERROR(-20002, 'Invalid BLOOD_UNITS.status value.');
    END IF;

    IF :NEW.expiry_date < TRUNC(SYSDATE) AND :NEW.status IN ('Available', 'Reserved') THEN
        RAISE_APPLICATION_ERROR(-20003, 'Expired blood units cannot be Available or Reserved.');
    END IF;
END;
/

-- 3) Audit trigger for BLOOD_UNITS status changes
CREATE OR REPLACE TRIGGER trg_blood_units_audit_status
AFTER UPDATE OF status ON blood_units
FOR EACH ROW
BEGIN
    IF NVL(:OLD.status, 'NULL') <> NVL(:NEW.status, 'NULL') THEN
        INSERT INTO blood_unit_status_audit (unit_id, old_status, new_status)
        VALUES (:NEW.unit_id, :OLD.status, :NEW.status);
    END IF;
END;
/

-- 4) Validation on TRANSFUSION_REQUESTS:
--    - units_required > 0
--    - request_date not in future
--    - controlled request status values
CREATE OR REPLACE TRIGGER trg_transfusion_requests_validate
BEFORE INSERT OR UPDATE ON transfusion_requests
FOR EACH ROW
BEGIN
    IF :NEW.units_required IS NULL OR :NEW.units_required <= 0 THEN
        RAISE_APPLICATION_ERROR(-20010, 'units_required must be greater than zero.');
    END IF;

    IF :NEW.request_date IS NULL THEN
        RAISE_APPLICATION_ERROR(-20011, 'request_date cannot be NULL.');
    END IF;

    IF :NEW.request_date > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20012, 'request_date cannot be in the future.');
    END IF;

    IF :NEW.status NOT IN ('Pending', 'Partially Fulfilled', 'Completed', 'Cancelled') THEN
        RAISE_APPLICATION_ERROR(-20013, 'Invalid TRANSFUSION_REQUESTS.status value.');
    END IF;
END;
/

-- 5) Validation on UNIT_TRANSFERS:
--    - prevent same source and destination
--    - prevent future transfers
CREATE OR REPLACE TRIGGER trg_unit_transfers_validate
BEFORE INSERT OR UPDATE ON unit_transfers
FOR EACH ROW
BEGIN
    IF :NEW.from_facility_id = :NEW.to_facility_id THEN
        RAISE_APPLICATION_ERROR(-20020, 'from_facility_id and to_facility_id must be different.');
    END IF;

    IF :NEW.transfer_date > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20021, 'transfer_date cannot be in the future.');
    END IF;
END;
/

-- 6) Validation on MATCH_DISPATCHES:
--    - non-negative distance
--    - dispatch date not in future
--    - controlled statuses
CREATE OR REPLACE TRIGGER trg_match_dispatches_validate
BEFORE INSERT OR UPDATE ON match_dispatches
FOR EACH ROW
BEGIN
    IF :NEW.distance_km < 0 THEN
        RAISE_APPLICATION_ERROR(-20030, 'distance_km must be non-negative.');
    END IF;

    IF :NEW.dispatch_date > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20031, 'dispatch_date cannot be in the future.');
    END IF;

    IF :NEW.status NOT IN ('Queued', 'In Transit', 'Arrived', 'Cancelled', 'Failed') THEN
        RAISE_APPLICATION_ERROR(-20032, 'Invalid MATCH_DISPATCHES.status value.');
    END IF;
END;
/

-- 7) Role-based data access views for APEX
CREATE OR REPLACE VIEW vw_admin_request_overview AS
SELECT
    r.request_id,
    r.request_date,
    r.urgency_level,
    r.units_required,
    r.status AS request_status,
    p.patient_id,
    p.first_name || ' ' || p.last_name AS patient_name,
    f.facility_id,
    f.facility_name
FROM transfusion_requests r
JOIN patients p ON p.patient_id = r.patient_id
JOIN facilities f ON f.facility_id = p.current_facility_id;
/

CREATE OR REPLACE VIEW vw_staff_request_overview AS
SELECT
    r.request_id,
    r.request_date,
    r.urgency_level,
    r.units_required,
    r.status AS request_status,
    p.patient_id,
    p.first_name || ' ' || p.last_name AS patient_name,
    p.current_facility_id AS facility_id
FROM transfusion_requests r
JOIN patients p ON p.patient_id = r.patient_id;
/

-- 8) Dashboard-ready aggregate views for APEX charts/cards
CREATE OR REPLACE VIEW vw_dashboard_inventory_by_status AS
SELECT
    status,
    COUNT(*) AS unit_count
FROM blood_units
GROUP BY status;
/

CREATE OR REPLACE VIEW vw_dashboard_requests_by_status AS
SELECT
    status,
    COUNT(*) AS request_count
FROM transfusion_requests
GROUP BY status;
/

CREATE OR REPLACE VIEW vw_dashboard_dispatch_performance AS
SELECT
    status,
    COUNT(*) AS dispatch_count,
    ROUND(AVG(distance_km), 2) AS avg_distance_km
FROM match_dispatches
GROUP BY status;
/

PROMPT Script completed successfully.
