PROMPT =========================================
PROMPT Workflow Gap Closure Script
PROMPT Adds request lifecycle, history, notifications, wrapper package
PROMPT =========================================

-- Re-runnable drops
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_transfusion_requests_history';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_transfusion_requests_notify';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_request_history_timeline';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_open_requests_by_facility';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_notifications_feed';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE blood_network_pkg';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE pkg_request_workflow';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE transfusion_request_history';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE app_notifications';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- 1) Request history table
CREATE TABLE transfusion_request_history (
    history_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id           NUMBER NOT NULL,
    operation_type       VARCHAR2(20) NOT NULL,
    old_status           VARCHAR2(50),
    new_status           VARCHAR2(50),
    old_units_required   NUMBER,
    new_units_required   NUMBER,
    changed_at           DATE DEFAULT SYSDATE NOT NULL,
    changed_by           VARCHAR2(255) DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER') NOT NULL,
    change_note          VARCHAR2(1000)
);
/

-- 2) Notification table (for APEX in-app notification center/report)
CREATE TABLE app_notifications (
    notification_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id           NUMBER,
    facility_id          NUMBER,
    recipient_role       VARCHAR2(30) NOT NULL,
    event_type           VARCHAR2(50) NOT NULL,
    message_text         VARCHAR2(1000) NOT NULL,
    is_read              CHAR(1) DEFAULT 'N' NOT NULL,
    created_at           DATE DEFAULT SYSDATE NOT NULL,
    created_by           VARCHAR2(255) DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER') NOT NULL
);
/

-- 3) History trigger for request lifecycle audit
CREATE OR REPLACE TRIGGER trg_transfusion_requests_history
AFTER INSERT OR UPDATE OR DELETE ON transfusion_requests
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO transfusion_request_history (
            request_id, operation_type, old_status, new_status, old_units_required, new_units_required, change_note
        )
        VALUES (
            :NEW.request_id, 'INSERT', NULL, :NEW.status, NULL, :NEW.units_required, 'Request created'
        );
    ELSIF UPDATING THEN
        IF NVL(:OLD.status, 'NULL') <> NVL(:NEW.status, 'NULL')
           OR NVL(:OLD.units_required, -1) <> NVL(:NEW.units_required, -1) THEN
            INSERT INTO transfusion_request_history (
                request_id, operation_type, old_status, new_status, old_units_required, new_units_required, change_note
            )
            VALUES (
                :NEW.request_id, 'UPDATE', :OLD.status, :NEW.status, :OLD.units_required, :NEW.units_required, 'Request updated'
            );
        END IF;
    ELSIF DELETING THEN
        INSERT INTO transfusion_request_history (
            request_id, operation_type, old_status, new_status, old_units_required, new_units_required, change_note
        )
        VALUES (
            :OLD.request_id, 'DELETE', :OLD.status, NULL, :OLD.units_required, NULL, 'Request deleted'
        );
    END IF;
END;
/

-- 4) Notification trigger for insert/status-change events
CREATE OR REPLACE TRIGGER trg_transfusion_requests_notify
AFTER INSERT OR UPDATE OF status ON transfusion_requests
FOR EACH ROW
DECLARE
    v_facility_id patients.current_facility_id%TYPE;
BEGIN
    SELECT p.current_facility_id
      INTO v_facility_id
      FROM patients p
     WHERE p.patient_id = COALESCE(:NEW.patient_id, :OLD.patient_id);

    IF INSERTING THEN
        INSERT INTO app_notifications (
            request_id, facility_id, recipient_role, event_type, message_text
        )
        VALUES (
            :NEW.request_id, v_facility_id, 'STAFF', 'REQUEST_CREATED',
            'Request #' || :NEW.request_id || ' created with urgency ' || :NEW.urgency_level
        );
    ELSIF UPDATING THEN
        IF NVL(:OLD.status, 'NULL') <> NVL(:NEW.status, 'NULL') THEN
            INSERT INTO app_notifications (
                request_id, facility_id, recipient_role, event_type, message_text
            )
            VALUES (
                :NEW.request_id, v_facility_id, 'STAFF', 'STATUS_CHANGED',
                'Request #' || :NEW.request_id || ' changed from "' || :OLD.status || '" to "' || :NEW.status || '"'
            );
        END IF;
    END IF;
END;
/

-- 5) Request workflow package: create/update/cancel/history
CREATE OR REPLACE PACKAGE pkg_request_workflow AS
    TYPE t_request_hist_rec IS RECORD (
        history_id         NUMBER,
        request_id         NUMBER,
        operation_type     VARCHAR2(20),
        old_status         VARCHAR2(50),
        new_status         VARCHAR2(50),
        changed_at         DATE,
        changed_by         VARCHAR2(255),
        change_note        VARCHAR2(1000)
    );
    TYPE t_request_hist_tab IS TABLE OF t_request_hist_rec;

    PROCEDURE create_request(
        p_patient_id       IN NUMBER,
        p_urgency_level    IN NUMBER,
        p_units_required   IN NUMBER,
        p_request_date     IN DATE DEFAULT TRUNC(SYSDATE),
        p_request_id       OUT NUMBER
    );

    PROCEDURE update_request(
        p_request_id       IN NUMBER,
        p_units_required   IN NUMBER,
        p_urgency_level    IN NUMBER,
        p_request_date     IN DATE
    );

    PROCEDURE cancel_request(
        p_request_id       IN NUMBER,
        p_reason           IN VARCHAR2 DEFAULT NULL
    );

    FUNCTION get_request_history(
        p_request_id       IN NUMBER
    ) RETURN t_request_hist_tab;
END pkg_request_workflow;
/

CREATE OR REPLACE PACKAGE BODY pkg_request_workflow AS
    PROCEDURE create_request(
        p_patient_id       IN NUMBER,
        p_urgency_level    IN NUMBER,
        p_units_required   IN NUMBER,
        p_request_date     IN DATE DEFAULT TRUNC(SYSDATE),
        p_request_id       OUT NUMBER
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM patients
         WHERE patient_id = p_patient_id;

        IF v_exists = 0 THEN
            RAISE_APPLICATION_ERROR(-20100, 'Invalid patient_id.');
        END IF;

        IF p_units_required <= 0 THEN
            RAISE_APPLICATION_ERROR(-20101, 'units_required must be > 0.');
        END IF;

        IF p_request_date > TRUNC(SYSDATE) THEN
            RAISE_APPLICATION_ERROR(-20102, 'request_date cannot be in the future.');
        END IF;

        SELECT NVL(MAX(request_id), 0) + 1
          INTO p_request_id
          FROM transfusion_requests;

        INSERT INTO transfusion_requests (
            request_id, patient_id, urgency_level, units_required, request_date, status
        )
        VALUES (
            p_request_id, p_patient_id, p_urgency_level, p_units_required, p_request_date, 'Pending'
        );
    END create_request;

    PROCEDURE update_request(
        p_request_id       IN NUMBER,
        p_units_required   IN NUMBER,
        p_urgency_level    IN NUMBER,
        p_request_date     IN DATE
    ) IS
        v_status transfusion_requests.status%TYPE;
    BEGIN
        SELECT status
          INTO v_status
          FROM transfusion_requests
         WHERE request_id = p_request_id;

        IF v_status IN ('Completed', 'Cancelled') THEN
            RAISE_APPLICATION_ERROR(-20110, 'Cannot edit a Completed/Cancelled request.');
        END IF;

        IF p_units_required <= 0 THEN
            RAISE_APPLICATION_ERROR(-20111, 'units_required must be > 0.');
        END IF;

        IF p_request_date > TRUNC(SYSDATE) THEN
            RAISE_APPLICATION_ERROR(-20112, 'request_date cannot be in the future.');
        END IF;

        UPDATE transfusion_requests
           SET units_required = p_units_required,
               urgency_level  = p_urgency_level,
               request_date   = p_request_date
         WHERE request_id = p_request_id;
    END update_request;

    PROCEDURE cancel_request(
        p_request_id       IN NUMBER,
        p_reason           IN VARCHAR2 DEFAULT NULL
    ) IS
        v_status transfusion_requests.status%TYPE;
    BEGIN
        SELECT status
          INTO v_status
          FROM transfusion_requests
         WHERE request_id = p_request_id;

        IF v_status = 'Cancelled' THEN
            RETURN;
        END IF;

        UPDATE transfusion_requests
           SET status = 'Cancelled'
         WHERE request_id = p_request_id;

        UPDATE match_dispatches
           SET status = 'Cancelled'
         WHERE request_id = p_request_id
           AND status IN ('Queued', 'In Transit');

        IF p_reason IS NOT NULL THEN
            UPDATE transfusion_request_history
               SET change_note = SUBSTR('Request cancelled. Reason: ' || p_reason, 1, 1000)
             WHERE history_id = (
                 SELECT MAX(history_id)
                   FROM transfusion_request_history
                  WHERE request_id = p_request_id
             );
        END IF;
    END cancel_request;

    FUNCTION get_request_history(
        p_request_id       IN NUMBER
    ) RETURN t_request_hist_tab IS
        v_hist t_request_hist_tab;
    BEGIN
        SELECT history_id,
               request_id,
               operation_type,
               old_status,
               new_status,
               changed_at,
               changed_by,
               change_note
          BULK COLLECT INTO v_hist
          FROM transfusion_request_history
         WHERE request_id = p_request_id
         ORDER BY changed_at DESC, history_id DESC;

        RETURN v_hist;
    END get_request_history;
END pkg_request_workflow;
/

-- 6) Wrapper package to match existing APEX calls (blood_network_pkg)
CREATE OR REPLACE PACKAGE blood_network_pkg AS
    FUNCTION calculate_distance_km(
        p_loc1_id IN NUMBER,
        p_loc2_id IN NUMBER
    ) RETURN NUMBER;

    PROCEDURE process_blood_matches;

    FUNCTION check_compatibility(
        p_donor_type_id IN NUMBER,
        p_recipient_type_id IN NUMBER
    ) RETURN VARCHAR2;
END blood_network_pkg;
/

CREATE OR REPLACE PACKAGE BODY blood_network_pkg AS
    FUNCTION calculate_distance_km(
        p_loc1_id IN NUMBER,
        p_loc2_id IN NUMBER
    ) RETURN NUMBER IS
    BEGIN
        RETURN pkg_blood_operations.calculate_distance_km(p_loc1_id, p_loc2_id);
    END calculate_distance_km;

    PROCEDURE process_blood_matches IS
    BEGIN
        pkg_blood_operations.process_blood_matches;
    END process_blood_matches;

    FUNCTION check_compatibility(
        p_donor_type_id IN NUMBER,
        p_recipient_type_id IN NUMBER
    ) RETURN VARCHAR2 IS
    BEGIN
        RETURN pkg_blood_operations.check_compatibility(p_donor_type_id, p_recipient_type_id);
    END check_compatibility;
END blood_network_pkg;
/

-- 7) Views for UI pages (history, open requests, notifications)
CREATE OR REPLACE VIEW vw_request_history_timeline AS
SELECT
    h.history_id,
    h.request_id,
    h.operation_type,
    h.old_status,
    h.new_status,
    h.old_units_required,
    h.new_units_required,
    h.changed_at,
    h.changed_by,
    h.change_note,
    p.first_name || ' ' || p.last_name AS patient_name,
    f.facility_name
FROM transfusion_request_history h
JOIN transfusion_requests r ON r.request_id = h.request_id
JOIN patients p ON p.patient_id = r.patient_id
JOIN facilities f ON f.facility_id = p.current_facility_id;
/

CREATE OR REPLACE VIEW vw_open_requests_by_facility AS
SELECT
    r.request_id,
    p.current_facility_id AS facility_id,
    f.facility_name,
    p.first_name || ' ' || p.last_name AS patient_name,
    bt.type_group || bt.rh_factor AS blood_type,
    r.urgency_level,
    r.units_required,
    r.status,
    r.request_date
FROM transfusion_requests r
JOIN patients p ON p.patient_id = r.patient_id
JOIN facilities f ON f.facility_id = p.current_facility_id
JOIN blood_types bt ON bt.blood_type_id = p.blood_type_id
WHERE r.status IN ('Pending', 'Partially Fulfilled');
/

CREATE OR REPLACE VIEW vw_notifications_feed AS
SELECT
    n.notification_id,
    n.request_id,
    n.facility_id,
    f.facility_name,
    n.recipient_role,
    n.event_type,
    n.message_text,
    n.is_read,
    n.created_at,
    n.created_by
FROM app_notifications n
LEFT JOIN facilities f ON f.facility_id = n.facility_id;
/

PROMPT Workflow gap closure script completed successfully.
