"""Application users for JWT auth (admin + staff)."""

from __future__ import annotations

import os
from typing import Sequence, Union

from alembic import op
from passlib.context import CryptContext
from sqlalchemy import text

revision: str = "005_app_users"
down_revision: Union[str, Sequence[str], None] = "004_run_oracle_plsql"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_pwd = CryptContext(schemes=["bcrypt"], deprecated="auto")


def upgrade() -> None:
    # Table may exist if a previous upgrade failed after CREATE but before Alembic stamped 005.
    op.execute(
        text(
            """
            BEGIN
                EXECUTE IMMEDIATE 'DROP TABLE app_users CASCADE CONSTRAINTS';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -942 THEN RAISE; END IF;
            END;
            """
        )
    )
    op.execute(
        text(
            """
            CREATE TABLE app_users (
                user_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email           VARCHAR2(255) NOT NULL,
                password_hash   VARCHAR2(255) NOT NULL,
                role            VARCHAR2(20) NOT NULL,
                created_at      DATE DEFAULT SYSDATE NOT NULL,
                CONSTRAINT uq_app_users_email UNIQUE (email),
                CONSTRAINT ck_app_users_role CHECK (role IN ('admin', 'staff'))
            )
            """
        )
    )
    admin_email = (os.environ.get("DEV_ADMIN_EMAIL") or "").strip()
    admin_password = os.environ.get("DEV_ADMIN_PASSWORD") or ""
    if not admin_email or not admin_password.strip():
        raise RuntimeError(
            "005_app_users: set DEV_ADMIN_EMAIL and DEV_ADMIN_PASSWORD in blood_donation_custom/.env "
            "(see .env.example). These are not hardcoded in the migration."
        )
    conn = op.get_bind()
    admin_hash = _pwd.hash(admin_password)
    conn.execute(
        text(
            "INSERT INTO app_users (email, password_hash, role) "
            "VALUES (:email, :password_hash, 'admin')"
        ),
        {"email": admin_email, "password_hash": admin_hash},
    )


def downgrade() -> None:
    op.execute(
        text(
            """
            BEGIN
                EXECUTE IMMEDIATE 'DROP TABLE app_users CASCADE CONSTRAINTS';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -942 THEN RAISE; END IF;
            END;
            """
        )
    )
